"""
EdgeGuard AI — YOLOv8 Training (Module 05 of ml work.txt)

PURPOSE
-------
Fine-tune a YOLOv8n model on the synthetic mining-truck dump dataset
generated by `dataset.py`. Saves the best weights + metrics so that
`infer.py` can serve predictions and `evaluate.py` can produce a
visual report.

OUTPUTS
-------
    engine1_vision/
    ├── models/
    │   ├── best.pt                 # YOLOv8n best checkpoint
    │   ├── last.pt                 # final epoch checkpoint
    │   ├── metrics.json            # mAP50, mAP50-95, P, R, F1, per-class
    │   └── vision_classes.json     # {0: truck_bed, 1: payload, 2: carryback, 3: hydraulic_ram}
    └── runs/detect/train/          # Ultralytics native run dir

WHY YOLOV8N
-----------
Nano is ~6MB, trains fastest on CPU. Our synthetic dataset is visually
consistent (geometric renderer) so a small model converges to high
mAP. Production deployments would upgrade to yolov8s/m/l once real
CCTV data is available.

WHY CPU-ONLY DEFAULTS
---------------------
The user has no CUDA setup. Training is wall-clock bounded (8-15 min
for 500 frames @ 30 epochs on a modern laptop). If a GPU is available
later, pass --device 0.

USAGE
-----
    python engine1_vision/train.py
    python engine1_vision/train.py --epochs 60 --batch 16
    python engine1_vision/train.py --device 0   # if GPU is available
"""

import argparse
import json
import shutil
from pathlib import Path

# synth_frames provides the canonical class map
from synth_frames import CLASS_MAP

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ENGINE_DIR  = Path(__file__).parent
DATA_YAML   = ENGINE_DIR / "data.yaml"
MODELS_DIR  = ENGINE_DIR / "models"
RUNS_DIR    = ENGINE_DIR / "runs"  # Ultralytics native output

DEFAULT_MODEL = "yolov8n.pt"
DEFAULT_EPOCHS = 30
DEFAULT_BATCH  = 8
DEFAULT_IMGSZ  = 640
DEFAULT_DEVICE = "cpu"


# ---------------------------------------------------------------------------
# Training entry point
# ---------------------------------------------------------------------------
def train(
    model_name: str = DEFAULT_MODEL,
    epochs:     int = DEFAULT_EPOCHS,
    batch:      int = DEFAULT_BATCH,
    imgsz:      int = DEFAULT_IMGSZ,
    device:     str = DEFAULT_DEVICE,
    patience:   int = 10,
    data_yaml:  Path = DATA_YAML,
    models_dir: Path = MODELS_DIR,
    runs_dir:   Path = RUNS_DIR,
):
    """Train YOLOv8n on the synthetic mining dataset."""
    if not Path(data_yaml).exists():
        raise FileNotFoundError(
            f"Dataset config not found: {data_yaml}. "
            f"Run `python engine1_vision/dataset.py --n 500` first."
        )

    # Heavy imports inside the function so this module is importable
    # even if torch/ultralytics is not yet installed.
    from ultralytics import YOLO

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    RUNS_DIR.mkdir(parents=True, exist_ok=True)

    # ---- Banner -----------------------------------------------------
    print(f"\n=== EdgeGuard AI — YOLOv8 Training ===\n")
    print(f"  Data:    {data_yaml}")
    print(f"  Model:   {model_name}")
    print(f"  Epochs:  {epochs}")
    print(f"  Batch:   {batch}")
    print(f"  Img sz:  {imgsz}")
    print(f"  Device:  {device}")
    print(f"  Patience:{patience}\n")

    # ---- Load model + train -----------------------------------------
    print(f"  Loading base model {model_name} ...")
    model = YOLO(model_name)

    print(f"\nTraining...\n")
    results = model.train(
        data=str(data_yaml),
        epochs=epochs,
        batch=batch,
        imgsz=imgsz,
        device=device,
        patience=patience,
        project=str(runs_dir),
        name="train",
        exist_ok=True,
        # Augmentations — Ultralytics defaults are strong, but we
        # explicitly set a few that suit the synthetic domain
        hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,
        degrees=10.0, translate=0.1, scale=0.5,
        fliplr=0.5, flipud=0.0,
        mosaic=1.0, mixup=0.1,
        # Save
        save=True, save_period=-1,
        # Verbose so we see epoch progress
        verbose=True,
        plots=True,
    )

    # ---- Save best.pt / last.pt to models/ -------------------------
    best_src = Path(results.save_dir) / "weights" / "best.pt"
    last_src = Path(results.save_dir) / "weights" / "last.pt"
    if best_src.exists():
        shutil.copy2(best_src, MODELS_DIR / "best.pt")
        print(f"\n  Saved best weights: {MODELS_DIR / 'best.pt'}")
    if last_src.exists():
        shutil.copy2(last_src, MODELS_DIR / "last.pt")
        print(f"  Saved last weights: {MODELS_DIR / 'last.pt'}")

    # ---- Persist class map -----------------------------------------
    class_json = {str(k): v for k, v in CLASS_MAP.items()}
    (MODELS_DIR / "vision_classes.json").write_text(json.dumps(class_json, indent=2))
    print(f"  Saved class map:     {MODELS_DIR / 'vision_classes.json'}")

    # ---- Persist metrics -------------------------------------------
    metrics = _extract_metrics(results, runs_dir)
    (MODELS_DIR / "metrics.json").write_text(json.dumps(metrics, indent=2, default=str))
    print(f"  Saved metrics:       {MODELS_DIR / 'metrics.json'}")

    print(f"\n=== Training complete ===\n")
    return metrics


def _extract_metrics(results, runs_dir: Path) -> dict:
    """Read Ultralytics results.csv + saved plots and bundle into a
    single JSON-serialisable dict."""
    csv_path = Path(results.save_dir) / "results.csv"
    metrics: dict = {
        "model":            results.model.args.get("model", "yolov8n.pt"),
        "epochs":           results.model.args.get("epochs"),
        "imgsz":            results.model.args.get("imgsz"),
        "batch":            results.model.args.get("batch"),
        "device":           results.model.args.get("device"),
        "save_dir":         str(results.save_dir),
    }
    if csv_path.exists():
        try:
            import pandas as pd
            df = pd.read_csv(csv_path)
            df.columns = [c.strip() for c in df.columns]
            metrics["per_epoch"] = df.to_dict(orient="records")
            # Best mAP50 / mAP50-95
            for col in ("metrics/mAP50(B)", "metrics/mAP50-95(B)",
                        "metrics/precision(B)", "metrics/recall(B)"):
                if col in df.columns:
                    short = col.split("/")[-1].split("(")[0]
                    metrics[f"best_{short}"] = float(df[col].max())
                    metrics[f"final_{short}"] = float(df[col].iloc[-1])
            # F1 = 2PR / (P+R) at final epoch
            p = metrics.get("final_precision(B)", 0.0)
            r = metrics.get("final_recall(B)", 0.0)
            metrics["final_F1"] = round(2 * p * r / max(p + r, 1e-9), 4) if (p + r) > 0 else 0.0
        except Exception as e:
            metrics["per_epoch_error"] = str(e)
    return metrics


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    p = argparse.ArgumentParser(description="EdgeGuard AI — YOLOv8 training")
    p.add_argument("--model",    default=DEFAULT_MODEL,    help="Base model (yolov8n/s/m/l)")
    p.add_argument("--epochs",   type=int, default=DEFAULT_EPOCHS)
    p.add_argument("--batch",    type=int, default=DEFAULT_BATCH)
    p.add_argument("--imgsz",    type=int, default=DEFAULT_IMGSZ)
    p.add_argument("--device",   default=DEFAULT_DEVICE,   help="cpu, 0, 0,1")
    p.add_argument("--patience", type=int, default=10)
    args = p.parse_args()

    train(
        model_name=args.model,
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        device=args.device,
        patience=args.patience,
    )


if __name__ == "__main__":
    main()
